### PR TITLE
Add composer json

### PR DESCRIPTION
**Pull request by sebastianthulin**
Adds basic composer json to enable adding plugin to packagist.

### CODE REVIEW

**Comment by sebastianthulin** [comment]
Hi! Any chance of this getting merged anytime soon?

**Comment by mcguffin** [comment]
@sebastianthulin Yes.

**Comment by sebastianthulin** [comment]
Thank you! Is it OK to register this at packagist, or would you rather keep control over this yourself?

**Comment by mcguffin** [comment]
Thanks for the offer! 
I just submitted it myself – already have a few other plugins running there.

**Comment by sebastianthulin** [comment]
Grate! Thank you for amazing work!

**Pull request merged**
